
version: "3.3"

services:
  myworking:
    container_name: myworking
    build:
      ./
    volumes:
      - ./root/.vimrc:/root/.vimrc
      - ./root/.bashrc:/root/.bashrc
      - ./code:/code
      - ~/.aws/:/root/.aws/
    environment:
      - MODE=BUSINESS
      - AWS_DEFAULT_REGION=ap-northeast-1
      - AWS_DEFAULT_OUTPUT=json