
version: "3.3"

services:
  myworking:
    container_name: myworking
    build:
      ./
    tty: true
    platform: linux/x86_64
    volumes:
      - ./root/.vimrc:/root/.vimrc
      - ./root/.bashrc:/root/.bashrc
      #- ./root/.config/nvim/init.lua:/root/.config/init.lua
      - ./code:/code
    environment:
      - MODE=PERSONAL
      